travis:
  secure:
    BINSTAR_TOKEN: f/2dpGPD6i30UZBKYqDOmVL8Q017xv+lbJIiAZcb4SgO2woc2/Ba69+6p5MFlpczFy6gWebOkrGJ8WXdWe3c5TpxzmwwXY8ns6UyEBTx/YwJ2YUuh6NPn5LYDeczIHO5m1M6wJVM5FwvgeDg/2o6Y/Q6HpgmR2lbkByNrtpSaN1+WngwMKs5/RmDvx8AD3vC8EzUHMh641R5SBKfVIHEmDfW1CdJjRkYXKFME/QczyXzdOvyuc4BWcHUcvhYWtNyAjr+j6MCKkazMliSM9cmh4l0hglz5RADlNmLuiKN06/v+i1vCJk0W3oXWNQZoZyxk4zCoqqYgzJ1LzmIBI2dY5n199n9p8sXGR9eRJKs0lavPG74XqwUUlo/Z42iTQsLz/vrgY1iA6IQTkz58QHu2p3B4DaKo6Fd69M+EI42rf+UkUEvQNohXyhAgMuuhD87zCw2V6dnC074xRz1+xkkJzAJItz8Nrbm7dAk0Qlq1v7XSB5NFKYatM0WGwEuul1ooxR+iN9OQGWaKtwRS477ciG6nt4XjCeKjcCBa/GmazkkyXHHQ0VG+JtWjIAavNobuDWtKcYL6wJs6+IhJpRrPEOGqvPjc4iVvzlJqGSaPgZ5SKtElxbID0eZOECgweaYzZ5GW60ZVrslGiakeFR9w720mjemj794LVUTBTjon6o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
