travis:
  secure:
    BINSTAR_TOKEN: OhERnPmOkK9PyM9KFReLZSCZcShdIVaJcJEnY3hBY+3GxlpCezEpp4C3uLTbU5qx/ex4NRO7EoFKm/kZfMt6RNd0GaGAi/R8H8lUL43Lb232kRSKCQW5de3oxgB5+ptxHWmn1SMd8kos5OhCSK1D9hPT8j/6AKQXdFWXrpZWKoTx/gL9NTdI1BFU7a5YA/YF2Z+SCxcJWBFNEQJKSkvWkJNKFknkPD5WGibq2RY+yEmN5WZkhT+SmtiFOcscnflBCTKDQP+ic5DzNqiPgNic1oA1G519Ipr1eDnZwLedP1+odzkPI4TOUtdULOx/jkqDqGkd2HxJbtItrLfOPffp07jQrknje3bPK0ELL4PuP+fHemF4k3eDwhA1k9JaqNYgcqzrAbjkLU1zNBqheWOj5s9vax9Z9aLdt6hXFlU7sew4wAGIuCoernZEqx5H1bHmplu35p2LoWrzYcLrj3yLFUiMDvTikd6HUgDtR8pWrt2ig6JLdZE/NezfFIioJUCp3R0klRI650KC8z2w6JLy2N4lMtVArMCVM1WmhRmMkcG389OFsn0i1vsCmVdA9CAMZe6I39p9A7Bwdyq8nUCdvs+NIA7ai63TOYvIbvj/F56k9u9rUawasdaMsBkNcOXPN5VdjXOwOoaRAwj9/JzqXovt+kp5clLHD9jm3AvMZtk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
